### ISSUE TITLE
Dataset request

### ISSUE THREAD

**Issue by fj-morales** [grammarly/gaqcorpus#1]
Hi, 

I've been following your research in the paper Creating a Domain-diverse Corpus for Theory-based Argument Quality Assessment.
I kindly request the dataset you mentioned will be publicly available.

Thanks.

**Comment by cnap** [comment]
Before accessing the dataset, you first need to gain access to the original data sources. These data are all available free of charge provided you request them from the original sources and agree to the respective license terms. Once you have gained access to the first three corpora listed above, please forward the confirmations to Courtney Napoles (courtney.napoles@grammarly.com), along with your affiliation and a short description of how you will be using the data, and we will provide access to the GAQCorpus. Please let us know if you have any questions.
